### PR TITLE
Correct regulator timming

### PR DESCRIPTION
**Pull request by scafroglia93**
Startup times kernel reduced

Based on AK
https://github.com/anarkia1976/AK-Angler/commit/d9880e422ba44eb26b3e58f7863c8fcc58c76ae6

### CODE REVIEW

**Comment by SferaDev** [comment]
@xboxfanj @TheCrazyLex @Grarak

**Comment by SferaDev** [comment]
Could you send it over gerrit.aospa.co?

We'll review the change over there!

Thanks :)

**Comment by scafroglia93** [comment]
Not in my HQ at the moment :(

**Comment by TheCrazyLex** [comment]
@SferaDev pls close

**Pull request closed without merging**
